In [4]:
import numpy as np

a = np.ndarray([3,2,3,4])

print(a)


[[[[0.00000000e+000 0.00000000e+000 0.00000000e+000 6.95212101e-310]
   [3.31023983e-322 9.18638659e-312 9.18636137e-312 9.18636138e-312]
   [9.18636138e-312 9.18636137e-312 9.18636138e-312 9.18636136e-312]]

  [[9.18638704e-312 9.18638706e-312 9.18636138e-312 9.18638705e-312]
   [9.18636136e-312 9.18638704e-312 9.18636137e-312 9.18636137e-312]
   [9.18636137e-312 9.18636136e-312 9.18636137e-312 9.18636137e-312]]]


 [[[9.18638704e-312 9.18636137e-312 9.18636138e-312 9.18636136e-312]
   [9.18636138e-312 9.18638705e-312 9.18636137e-312 9.18636137e-312]
   [9.18636137e-312 9.18636137e-312 9.18636136e-312 9.18636138e-312]]

  [[9.18636137e-312 9.18636137e-312 9.18638705e-312 9.18638705e-312]
   [9.18636138e-312 9.18636137e-312 9.18636137e-312 9.18636137e-312]
   [9.18636138e-312 9.18636138e-312 9.18638705e-312 9.18636137e-312]]]


 [[[9.18636138e-312 9.18636137e-312 9.18636139e-312 9.18636138e-312]
   [9.18636138e-312 9.18636138e-312 9.18636138e-312 9.18638705e-312]
   [9.18636138e-312 9.